### ISSUE TITLE
模型中图片尺寸的问题

### ISSUE THREAD

**Issue by yifffdas** [zifeng-radxa/Real-ESRGAN-tpu_Web#1]
请问，real_ESRGANfp32的模型能在up_cli.py上用我的图片成功运行，但是int8的模型用相同的图片却运行不了，
[BMRT][load_bmodel:1503] INFO:pre net num: 0, load net num: 1
[BMRT][load_tpu_module:1575] INFO:loading firmare in bmodel
[tid=263231c0] INFO: NetName: real_esrgan
[tid=263231c0] INFO:   Input 0) 'input.1' shape=[ 1 3 480 640 ] dtype=UINT8 scale=254.998
[tid=263231c0] INFO:   Output 0) '208_Add' shape=[ 1 3 1920 2560 ] dtype=INT8 scale=0.00826153
  0%|                                                                                                                                                                                      | 0/1 [00:00<?, ?it/s]runtime_error, [tid=517fa640] FATAL: assert inTensors[i]->get_dtype()(3)==input.tensors[i].dtype(0)

terminate called after throwing an instance of 'std::runtime_error'
  what():  [tid=517fa640] FATAL: assert inTensors[i]->get_dtype()(3)==input.tensors[i].dtype(0)

Aborted (core dumped)

**Comment by zifeng-radxa** [comment]
hi, please make sure your input type is UINT8
